{"name": "用户注册登录删除-预期失败", "status": "skipped", "statusDetails": {"message": "AssertionError: 接口返回码是 【 2005 】, 返回信息：手机号已被注册！！！ \nassert False is True\n +  where False = <core.result_base.ResultBase object at 0x10a1cfdf0>.success", "trace": "self = <testcases.scenario_test.test_03_register_login_delete.TestRegLogDelete object at 0x10a1cffd0>\ntestcase_data = {'address': '深圳市宝安区', 'admin_pwd': '123456', 'admin_user': 'wintest4', 'except_code': 3004, ...}\n\n    @allure.story(\"用例--注册/登录/删除--预期失败\")\n    @allure.description(\"该用例是针对 注册-登录-删除 场景的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录删除-预期失败\")\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason=\"xfail示例：预期失败的用例，如存在尚未解决的Bug等\")\n    @pytest.mark.usefixtures(\"delete_register_user\")\n    def test_user_register_login_delete_fail(self, testcase_data):\n        username = testcase_data[\"username\"]\n        password = testcase_data[\"password\"]\n        telephone = testcase_data[\"telephone\"]\n        sex = testcase_data[\"sex\"]\n        address = testcase_data[\"address\"]\n        admin_user = testcase_data[\"admin_user\"]\n        admin_pwd = testcase_data[\"admin_pwd\"]\n        except_result = testcase_data[\"except_result\"]\n        except_code = testcase_data[\"except_code\"]\n        except_msg = testcase_data[\"except_msg\"]\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = register_user(username, password, telephone, sex, address)\n        step_1(username, password, telephone, sex, address)\n>       assert result.success is True, result.error\nE       AssertionError: 接口返回码是 【 2005 】, 返回信息：手机号已被注册！！！ \nE       assert False is True\nE        +  where False = <core.result_base.ResultBase object at 0x10a1cfdf0>.success\n\ntestcases/scenario_test/test_03_register_login_delete.py:87: AssertionError"}, "description": "该用例是针对 注册-登录-删除 场景的测试", "steps": [{"name": "步骤1 ==>> 注册用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "telephone", "value": "'13599999999'"}, {"name": "sex", "value": "'1'"}, {"name": "address", "value": "'深圳市宝安区'"}], "start": 1744699124482, "stop": 1744699124482}], "attachments": [{"name": "log", "source": "a3bb2c4b-6e55-4bca-a7c8-de82b4ca9b2d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d022d9f9-ee75-45b6-8285-b0eeb11b4a92-attachment.txt", "type": "text/plain"}], "start": 1744699124388, "stop": 1744699124482, "uuid": "89515675-5608-4210-8afd-758214cde0bb", "historyId": "7164a98ce91bd9f479af2fa0b0f95820", "testCaseId": "b7d06749c352697ac0c07e2d04f5e9d2", "fullName": "testcases.scenario_test.test_03_register_login_delete.TestRegLogDelete#test_user_register_login_delete_fail", "labels": [{"name": "feature", "value": "场景：用户注册-用户登录-删除用户"}, {"name": "epic", "value": "针对业务场景的测试"}, {"name": "story", "value": "用例--注册/登录/删除--预期失败"}, {"name": "severity", "value": "minor"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "testcases.scenario_test"}, {"name": "suite", "value": "test_03_register_login_delete"}, {"name": "subSuite", "value": "TestRegLogDelete"}, {"name": "host", "value": "192.168.10.5"}, {"name": "thread", "value": "23339-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.scenario_test.test_03_register_login_delete"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}