{"uuid": "4d522c1c-6e0d-4364-b41f-d5c62f483c42", "children": ["02435043-8ef2-4fff-ba13-dd9bf25bf0bf", "0eba0c80-a6e2-4b93-b871-007b26c43506", "2bb3a018-1e16-4486-b3f5-7261a849ea57", "b0c1245c-b340-4ac5-a77a-9206a6a37879", "fe56a11b-a17b-4edd-8d7f-9a7212edd07b"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'Response' object has no attribute 'response'\n", "trace": "  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/testcases/conftest.py\", line 57, in login_fixture\n    yield loginInfo.response.json()\n"}, "steps": [{"name": "前置步骤 ==>> 管理员用户登录", "status": "passed", "parameters": [{"name": "username", "value": "'wintest'"}, {"name": "password", "value": "'123456'"}], "start": 1744987804451, "stop": 1744987804451}], "start": 1744987804385, "stop": 1744987804452}], "start": 1744987804385, "stop": 1744987806648}