{"uuid": "c79c27b5-037e-4b4f-8737-0354036499cc", "children": ["a7b089cd-e67d-4b2a-a3da-14b01bc783bc", "b866ca85-158e-4ced-9d6e-d5a99e57b20d", "630b8e23-9598-4858-9829-a894a7bc0efd", "6341d0fe-b0ce-4360-beb9-da2e8fdabe21", "e4a62c3a-ec3e-45aa-9312-c845c5d21f7e"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'Response' object has no attribute 'response'\n", "trace": "  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/testcases/conftest.py\", line 57, in login_fixture\n    yield loginInfo.response.json()\n"}, "steps": [{"name": "前置步骤 ==>> 管理员用户登录", "status": "passed", "parameters": [{"name": "username", "value": "'wintest'"}, {"name": "password", "value": "'123456'"}], "start": 1744986708492, "stop": 1744986708492}], "start": 1744986708398, "stop": 1744986708492}], "start": 1744986708398, "stop": 1744986710585}