{"uuid": "ef9edc06-a258-4487-94f0-ceb6d36071a0", "children": ["13196a89-aedf-429a-a36e-0522c8d8fd0d", "f12f1eb2-6869-4557-b816-ed05c661ce7f", "cf7b8c1b-931d-4250-bc8a-b935fdec10b7", "3bb85d0a-6878-4163-83ea-6ad653620150", "86869887-946a-43dc-a278-c7848ee85ff3"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'Response' object has no attribute 'response'\n", "trace": "  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/testcases/conftest.py\", line 57, in login_fixture\n    yield loginInfo.response.json()\n"}, "steps": [{"name": "前置步骤 ==>> 管理员用户登录", "status": "passed", "parameters": [{"name": "username", "value": "'wintest'"}, {"name": "password", "value": "'123456'"}], "start": 1744988150726, "stop": 1744988150727}], "start": 1744988150662, "stop": 1744988150727}], "start": 1744988150662, "stop": 1744988152892}