{"name": "测试数据：【 wintest4，1234567，False，1002，用户名或密码错误】", "status": "passed", "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'wintest4'"}], "start": 1745030798103, "stop": 1745030798104}], "attachments": [{"name": "log", "source": "441eb3fd-17a8-411d-a75e-9e8c2d9ef462-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1fe70316-3f78-4584-8d10-84638e79479b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'wintest4'"}, {"name": "password", "value": "'1234567'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "1002"}, {"name": "except_msg", "value": "'用户名或密码错误'"}], "start": 1745030798033, "stop": 1745030798104, "uuid": "b8b75c9a-f0d4-4863-8d0d-e16a0b6700df", "historyId": "561292754cab8afa6b525b9347f6d1a0", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "192.168.10.5"}, {"name": "thread", "value": "45216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "https://blog.csdn.net/", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://blog.csdn.net/", "name": "点击，跳转到对应BUG的链接地址"}]}