{"uid":"405f436da8c2e479","name":"测试数据：【 wintest，123456，True，0，登录成功】","fullName":"testcases.api_test.test_03_login.TestUserLogin#test_login_user","historyId":"4ab02ebad4baabe28d2fb7352ad2343a","time":{"start":1744699252084,"stop":1744699252144,"duration":60},"description":"该用例是针对获取用户登录接口的测试","descriptionHtml":"<p>该用例是针对获取用户登录接口的测试</p>\n","status":"failed","statusMessage":"AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x10b573d60>.success","statusTrace":"self = <testcases.api_test.test_03_login.TestUserLogin object at 0x10b574370>\nusername = 'wintest', password = '123456', except_result = True, except_code = 0\nexcept_msg = '登录成功'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nE       assert False == True\nE        +  where False = <core.result_base.ResultBase object at 0x10b573d60>.success\n\ntestcases/api_test/test_03_login.py:30: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"该用例是针对获取用户登录接口的测试","status":"failed","statusMessage":"AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x10b573d60>.success","statusTrace":"self = <testcases.api_test.test_03_login.TestUserLogin object at 0x10b574370>\nusername = 'wintest', password = '123456', except_result = True, except_code = 0\nexcept_msg = '登录成功'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nE       assert False == True\nE        +  where False = <core.result_base.ResultBase object at 0x10b573d60>.success\n\ntestcases/api_test/test_03_login.py:30: AssertionError","steps":[{"name":"步骤1 ==>> 登录用户","time":{"start":1744699252143,"stop":1744699252144,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"username","value":"'wintest'"}],"stepsCount":0,"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false}],"attachments":[{"uid":"6da5b496ed0f2404","name":"log","source":"6da5b496ed0f2404.txt","type":"text/plain","size":953},{"uid":"3e7d4bdb5172b971","name":"stderr","source":"3e7d4bdb5172b971.txt","type":"text/plain","size":1185}],"parameters":[],"stepsCount":1,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":2,"attachmentStep":false},"afterStages":[],"labels":[{"name":"feature","value":"用户登录模块"},{"name":"severity","value":"normal"},{"name":"epic","value":"针对单个接口的测试"},{"name":"story","value":"用例--登录用户"},{"name":"tag","value":"single"},{"name":"parentSuite","value":"testcases.api_test"},{"name":"suite","value":"test_03_login"},{"name":"subSuite","value":"TestUserLogin"},{"name":"host","value":"192.168.10.5"},{"name":"thread","value":"23437-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.api_test.test_03_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"except_code","value":"0"},{"name":"except_msg","value":"'登录成功'"},{"name":"except_result","value":"True"},{"name":"password","value":"'123456'"},{"name":"username","value":"'wintest'"}],"links":[{"name":"点击，跳转到对应用例的链接地址","url":"https://www.cnblogs.com/wintest","type":"test_case"},{"name":"点击，跳转到对应BUG的链接地址","url":"https://www.cnblogs.com/wintest","type":"issue"}],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"3a39dc6f9e6f1757","status":"failed","statusDetails":"AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x10bbb5dc0>.success","time":{"start":1744699198391,"stop":1744699198458,"duration":67}},{"uid":"a00e01232b23987c","status":"failed","statusDetails":"AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x10a16fb50>.success","time":{"start":1744699122724,"stop":1744699122820,"duration":96}},{"uid":"20aef0287d528595","status":"failed","statusDetails":"AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x109e36a90>.success","time":{"start":1744699040988,"stop":1744699041047,"duration":59}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["single"]},"source":"405f436da8c2e479.json","parameterValues":["0","'登录成功'","True","'123456'","'wintest'"]}