{"uid":"ff00c772604d265b","name":"测试数据：【 wintest，123456，True，0，登录成功】","fullName":"testcases.api_test.test_03_login.TestUserLogin#test_login_user","historyId":"4ab02ebad4baabe28d2fb7352ad2343a","time":{"start":1744708529656,"stop":1744708529756,"duration":100},"description":"该用例是针对获取用户登录接口的测试","descriptionHtml":"<p>该用例是针对获取用户登录接口的测试</p>\n","status":"failed","statusMessage":"AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x1041877f0>.success","statusTrace":"self = <testcases.api_test.test_03_login.TestUserLogin object at 0x1040eed60>\nusername = 'wintest', password = '123456', except_result = True, except_code = 0\nexcept_msg = '登录成功'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://blog.csdn.net/\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://blog.csdn.net/\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nE       assert False == True\nE        +  where False = <core.result_base.ResultBase object at 0x1041877f0>.success\n\ntestcases/api_test/test_03_login.py:30: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"该用例是针对获取用户登录接口的测试","status":"failed","statusMessage":"AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x1041877f0>.success","statusTrace":"self = <testcases.api_test.test_03_login.TestUserLogin object at 0x1040eed60>\nusername = 'wintest', password = '123456', except_result = True, except_code = 0\nexcept_msg = '登录成功'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://blog.csdn.net/\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://blog.csdn.net/\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 1003 】, 返回信息：用户名不存在！！！ \nE       assert False == True\nE        +  where False = <core.result_base.ResultBase object at 0x1041877f0>.success\n\ntestcases/api_test/test_03_login.py:30: AssertionError","steps":[{"name":"步骤1 ==>> 登录用户","time":{"start":1744708529754,"stop":1744708529755,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"username","value":"'wintest'"}],"stepsCount":0,"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false}],"attachments":[{"uid":"92c3b0996e4eb59c","name":"log","source":"92c3b0996e4eb59c.txt","type":"text/plain","size":953},{"uid":"f95139e7ccd6b676","name":"stderr","source":"f95139e7ccd6b676.txt","type":"text/plain","size":1185}],"parameters":[],"stepsCount":1,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":2,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"针对单个接口的测试"},{"name":"feature","value":"用户登录模块"},{"name":"severity","value":"normal"},{"name":"story","value":"用例--登录用户"},{"name":"tag","value":"single"},{"name":"parentSuite","value":"testcases.api_test"},{"name":"suite","value":"test_03_login"},{"name":"subSuite","value":"TestUserLogin"},{"name":"host","value":"192.168.10.5"},{"name":"thread","value":"24590-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.api_test.test_03_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"except_code","value":"0"},{"name":"except_msg","value":"'登录成功'"},{"name":"except_result","value":"True"},{"name":"password","value":"'123456'"},{"name":"username","value":"'wintest'"}],"links":[{"name":"点击，跳转到对应用例的链接地址","url":"https://blog.csdn.net/","type":"test_case"},{"name":"点击，跳转到对应BUG的链接地址","url":"https://blog.csdn.net/","type":"issue"}],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["single"]},"source":"ff00c772604d265b.json","parameterValues":["0","'登录成功'","True","'123456'","'wintest'"]}